indices = {
    'index': -34,
    'date': -33,
    'time_of_day': -32,
    'quality_flag_index': -31,
    'amplitude_flag_index': -30,
    'sector': -29,
    'IA': -28,
    'EA': -27,
    'CA': -26,
    'IT': -25,
    'ET': -24,
    'EIT': -23,
    'EIC': -22,
    'ICC': -21,
    'PA': -20,
    'PET': -19,
    'EVD': -18,
    'ICP': -17,
    'ECP': -16,
    'CCP': -15,
    'PCP': -14,
    'HV': -13,
    'R': -12,
    'LON': -11,
    'LAT': -10,
    'R_E': -9,
    'D_JUP': -8,
    'rotation_angle_index': -7,
    'solar_lon_index': -6,
    'solar_lat_index': -5,
    'velocity_index': -4,
    'velocity_error_index': -3,
    'mass_index': -2,
    'mass_error_index': -1,
    'first_data_line': 6

}
